FROM node:10.15-alpine
LABEL author=”tyncht”
# COPY all the files from Current Directory into the Container

# Install the Project Dependencies like Express Framework
RUN yum Install httpd

COPY index.html /var/www/html

# Tell that this image is going to Open a Port 
EXPOSE 80

# Default Command to launch the Application
CMD ["npm", "start"]