name: Deploy Infrastructure

on:
  push:
    branches:
      - master
      - test

jobs:
  tf_fmt:
    name: Docker build and Deploy pipeline
    runs-on: ubuntu-latest
    steps:

    - name: Set env BRANCH
      run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

    - name: Set env NEED
      run: |
        set -e
        echo $GITHUB_ENV
        export GITHUB_USERNAME="${{ github.actor }}"
        
        if [[ $BRANCH == 'master' && $GITHUB_EVENT_NAME == 'push' ]]; then
            echo "ENV=prod" >> "$GITHUB_ENV"
            export ENV=prod

        elif [[ $BRANCH == 'dev' && $GITHUB_EVENT_NAME == 'push' ]]; then
            echo "ENV=dev" >> "$GITHUB_ENV"
            export ENV=dev

        elif [[ $BRANCH == 'qa' && $GITHUB_EVENT_NAME == 'push' ]]; then
            echo "ENV=qa" >> "$GITHUB_ENV"
            export ENV=qa

        fi
        echo "PUSH_DOCKER_ENDPOINT=$GITHUB_USERNAME/weather-station:$ENV" >> "$GITHUB_ENV"

    - name: Cloning the repo
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: deployments/docker
        push: true
        tags: tyncha/weather-station:prod

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: deployments/terraform
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: deployments/terraform
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  second_pipeline:
    name: Docker build and Deploy pipeline
    runs-on: ubuntu-latest
    steps:

    - name: Cloning the repo
      uses: actions/checkout@v1

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: deployments/terraform
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: deployments/terraform
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

